"""Initial schema

Revision ID: 6479bd4201e7
Revises: 
Create Date: 2026-10-03 13:34:00.945868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6479bd4201e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membres_email'), 'membres', ['email'], unique=True)
    op.create_index(op.f('ix_membres_id'), 'membres', ['id'], unique=False)
    op.create_index(op.f('ix_membres_telegram_user_id'), 'membres', ['telegram_user_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_transaction', sa.Enum('DEPENSE', 'REVENU', 'REMBOURSEMENT', name='typetransactionenum'), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_transaction', sa.Date(), nullable=False),
    sa.Column('id_payeur', sa.Integer(), nullable=True),
    sa.Column('id_auteur', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('TELEGRAM', 'WEB', name='sourceenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_auteur'], ['membres.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_payeur'], ['membres.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date_transaction'), 'transactions', ['date_transaction'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_id_auteur'), 'transactions', ['id_auteur'], unique=False)
    op.create_index(op.f('ix_transactions_id_payeur'), 'transactions', ['id_payeur'], unique=False)
    op.create_table('transaction_participants',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_membre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_membre'], ['membres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transaction', 'id_membre')
    )
    op.create_index(op.f('ix_transaction_participants_id_membre'), 'transaction_participants', ['id_membre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_participants_id_membre'), table_name='transaction_participants')
    op.drop_table('transaction_participants')
    op.drop_index(op.f('ix_transactions_id_payeur'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id_auteur'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date_transaction'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_membres_telegram_user_id'), table_name='membres')
    op.drop_index(op.f('ix_membres_id'), table_name='membres')
    op.drop_index(op.f('ix_membres_email'), table_name='membres')
    op.drop_table('membres')
    # ### end Alembic commands ###
